---
title: "scopus_analysis"
author: "daniellembecker"
date: "2024-02-01"
output: html_document
---

# Using the analysis output from [Scopus](https://www.scopus.com/term/analyzer.uri?sort=plf-f&src=s&sid=c3cad66d9c803eb9e767bdd52c487fb7&sot=a&sdt=a&sl=16&s=ALL%28sealifebase%29&origin=resultslist&count=10&analyzeResults=Analyze+results) where I searched SeaLifeBase citations.


# Load libraries

```{r}
library(ggplot2)
library(ggthemes)
library(tidyverse)
library(dplyr)
library(utils)
install.packages(c("leaflet"))
library(leaflet)
```

# Load all data files

```{r}

# Specify the folder path
folder_path <- "data/scopus_analyze_data/"

# Get a list of all CSV files in the folder
csv_files <- list.files(folder_path, pattern = "\\.csv$", full.names = TRUE)

# Read and skip the first seven rows for each CSV file, store in a list
all_data <- map(csv_files, ~{
  current_data <- read_csv(.x, skip = 7)
  # Rename the second column to the number of documents
  colnames(current_data)[2] <- 'number_documents'
  current_data
})

#name individual files
affiliation <- all_data[[1]]
author <- all_data[[2]]
country <- all_data[[3]]
doctype <- all_data[[4]]
funding.sponsor <- all_data[[5]]
# Rename the first column to 'funding_sponsor'
colnames(funding.sponsor)[1] <- 'funding_sponsor'
source <- all_data[[6]]
subject <- all_data[[7]]
year <- all_data[[8]]

# Save each data frame to a separate CSV file
save_data_frame <- function(data_frame, file_name) {
  output_file <- file.path("output/scopus_csv/", paste0(file_name, ".csv"))
  write.csv(data_frame, file = output_file, row.names = FALSE)
}

# Save each data frame
save_data_frame(affiliation, "affiliation")
save_data_frame(author, "author")
save_data_frame(country, "country")
save_data_frame(doctype, "doctype")
save_data_frame(funding.sponsor, "funding_sponsor")
save_data_frame(source, "source")
save_data_frame(subject, "subject")
save_data_frame(year, "year")

```


# Figure 1 for SeaLifeBase
```{r}

# Create a bar chart
year.plot <- year %>%
  ggplot(aes(x=YEAR, y=number_documents))+
  geom_line() + 
  geom_point() +
  theme_classic()+
  theme(axis.text.x = element_text(angle = 0)) +
  ylab("Scopus Citations")+
  xlab("Year")+
  theme(axis.text.x = element_text(angle = 0, margin = margin(t = 10)),  # Adjust the margin as needed
        axis.title = element_text(size = 16), # Adjust the size of x and y axis labels
        axis.text = element_text(size = 16)) + # Adjust the margin as needed
   scale_x_continuous(breaks = unique(year$YEAR), limits = c(min(year$YEAR), max(year$YEAR) - 1), expand = c(0, 0))+
  scale_y_continuous(limits = c(0, 90), breaks = seq(0, 90, by = 10), expand = c(0, 0));year.plot

# Save the ggplot to a file (e.g., in PNG format)
ggsave("output/scopus_plots/year_output.png", plot = year.plot, width = 15, height = 6, dpi = 300)

```

# Comparing two citation lists generated by scopus for SeaLifeBase, first is 404 citations because we searched SeaLifeBase only, the 325 list is a search for SeaLifeBase and Palomares and Pauly

```{r}
#read in two data frames for comparison of citations

# Assuming your CSV file is in the working directory
sealifebase_325 <- read.csv("data/citation_list_master/scopus_extracat_citations_325.csv")

sealifebase_404 <- read.csv("data/citation_list_master/scopus_sealifebase_404.csv")

# Find citations that are in df1 but not in df2
unique_to_df1 <- anti_join(sealifebase_325, sealifebase_404)

# Print the results
cat("Citations unique to df1:", nrow(unique_to_df1), "\n")
print(unique_to_df1)
#9

# Find citations that are in df2 but not in df1
unique_to_df2 <- anti_join(sealifebase_404, sealifebase_325)

# Print the results
cat("\nCitations unique to df2:", nrow(unique_to_df2), "\n")
print(unique_to_df2)
#88

# Find citations that are common to both data frames
common_citations <- intersect(sealifebase_325, sealifebase_404)

# Print the results
cat("\nCommon citations:", nrow(common_citations), "\n")
print(common_citations)
#316

#first checked and all 9 citation titles in df1 above are in df2
#looking at scopus for 88 citation titles to confirm they are found in df2

```







